import pool from "@/lib/db";

export async function GET(req) {
  try {
    const { searchParams } = new URL(req.url);

    const from = searchParams.get("from");
    const to = searchParams.get("to");
    const type = searchParams.get("type");

    if (!from || !to || !type) {
      return Response.json(
        {
          error: "from, to and type are required",
        },
        { status: 400 }
      );
    }

    // ================================================================
    // COMMON DATE RANGE
    //
    // Uses Asia/Kolkata so dashboard dates represent
    // the actual Indian calendar day.
    // ================================================================

    const dateCondition = `
      server_timestamp >= (
        $1::date AT TIME ZONE 'Asia/Kolkata'
      )
      AND server_timestamp < (
        ($2::date + INTERVAL '1 day')
        AT TIME ZONE 'Asia/Kolkata'
      )
    `;

    // ================================================================
    // EVENTS
    //
    // Returns ALL events independently from page views.
    // ================================================================

    if (type === "events") {
      const result = await pool.query(
        `
        SELECT
          id,
          event,
          visitor_id,
          session_id,
          page,
          full_url,
          city,
          region,
          country,
          referrer,
          user_agent,
          event_timestamp,
          server_timestamp
        FROM events
        WHERE ${dateCondition}
        ORDER BY server_timestamp DESC
        LIMIT 5000
        `,
        [from, to]
      );

      return Response.json({
        details: result.rows,
      });
    }

    // ================================================================
    // VISITORS
    //
    // One row per unique visitor_id.
    //
    // event_count = ALL events generated by the visitor
    // page_views  = ONLY page_view events
    // unique_pages = distinct pages visited
    //
    // NULL visitor_id values are excluded.
    // ================================================================

    if (type === "visitors") {
      const result = await pool.query(
        `
        SELECT
          visitor_id,

          MAX(city) AS city,
          MAX(region) AS region,
          MAX(country) AS country,

          MIN(server_timestamp) AS first_seen,
          MAX(server_timestamp) AS last_seen,

          COUNT(*) AS event_count,

          COUNT(*) FILTER (
            WHERE event = 'page_view'
          ) AS page_views,

          COUNT(
            DISTINCT page
          ) FILTER (
            WHERE page IS NOT NULL
          ) AS unique_pages

        FROM events

        WHERE ${dateCondition}

          AND visitor_id IS NOT NULL

        GROUP BY visitor_id

        ORDER BY
          page_views DESC,
          event_count DESC,
          last_seen DESC

        LIMIT 5000
        `,
        [from, to]
      );

      return Response.json({
        details: result.rows,
      });
    }

    // ================================================================
    // SESSIONS
    //
    // One row per session_id.
    // ================================================================

    if (type === "sessions") {
      const result = await pool.query(
        `
        SELECT
          session_id,

          (
            ARRAY_AGG(
              visitor_id
              ORDER BY server_timestamp ASC
            ) FILTER (
              WHERE visitor_id IS NOT NULL
            )
          )[1] AS visitor_id,

          (
            ARRAY_AGG(
              city
              ORDER BY server_timestamp DESC
            ) FILTER (
              WHERE city IS NOT NULL
            )
          )[1] AS city,

          (
            ARRAY_AGG(
              region
              ORDER BY server_timestamp DESC
            ) FILTER (
              WHERE region IS NOT NULL
            )
          )[1] AS region,

          (
            ARRAY_AGG(
              country
              ORDER BY server_timestamp DESC
            ) FILTER (
              WHERE country IS NOT NULL
            )
          )[1] AS country,

          MIN(server_timestamp) AS started_at,

          MAX(server_timestamp) AS last_activity,

          COUNT(*) AS event_count,

          COUNT(
            DISTINCT page
          ) FILTER (
            WHERE page IS NOT NULL
          ) AS unique_pages

        FROM events

        WHERE ${dateCondition}

          AND session_id IS NOT NULL

        GROUP BY session_id

        ORDER BY
          last_activity DESC

        LIMIT 5000
        `,
        [from, to]
      );

      return Response.json({
        details: result.rows,
      });
    }

    // ================================================================
    // PAGE VIEWS
    //
    // Page Views are calculated independently from Total Events.
    //
    // page_views      = total page_view events
    // unique_visitors = distinct visitor_id values generating page views
    // ================================================================

    if (type === "page_views") {
      const result = await pool.query(
        `
        SELECT
          page,

          COUNT(*) FILTER (
            WHERE event = 'page_view'
          ) AS page_views,

          COUNT(
            DISTINCT visitor_id
          ) FILTER (
            WHERE event = 'page_view'
              AND visitor_id IS NOT NULL
          ) AS unique_visitors,

          MIN(server_timestamp)
            FILTER (
              WHERE event = 'page_view'
            ) AS first_viewed,

          MAX(server_timestamp)
            FILTER (
              WHERE event = 'page_view'
            ) AS last_viewed

        FROM events

        WHERE ${dateCondition}

        GROUP BY page

        ORDER BY
          page_views DESC,
          unique_visitors DESC

        LIMIT 500
        `,
        [from, to]
      );

      return Response.json({
        details: result.rows,
      });
    }

    // ================================================================
    // INVALID TYPE
    // ================================================================

    return Response.json(
      {
        error: "Invalid type",
      },
      { status: 400 }
    );
  } catch (err) {
    console.error("[KPI DETAILS ERROR]", err);

    return Response.json(
      {
        error: "KPI details fetch failed",
      },
      {
        status: 500,
      }
    );
  }
}